<?php
require_once __DIR__ . '/includes/layout.php'; require_once __DIR__ . '/includes/participation.php'; require_once __DIR__ . '/includes/grading_ui.php';
$user = require_role('teacher'); $classroomId = (int) ($_GET['classroom_id'] ?? 0); $quizId = (int) ($_GET['quiz_id'] ?? 0);
$classroom = find_classroom($classroomId);
if (!$classroom || (int) $classroom['teacher_id'] !== (int) $user['id']) { http_response_code(403); exit('Classroom access denied.'); }
$quiz = classroom_quiz($classroom, $quizId); if (!$quiz) { http_response_code(404); exit('Quiz not found.'); }
$GLOBALS['quizweb_current_classroom_id'] = $classroomId; $error = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    require_form_csrf(); $pdo = db();
    try {
        $studentId = grading_student_id($classroom, $_POST['student_id'] ?? '');
        $body = grading_text($_POST['body'] ?? null, 'Reminder message', 500);
        $pdo->beginTransaction(); $lock = $pdo->prepare('SELECT * FROM classrooms WHERE id = ? FOR UPDATE'); $lock->execute([$classroomId]);
        $fresh = hydrate_classroom($lock->fetch()); grading_require_teacher($fresh, $user); grading_student_id($fresh, $studentId);
        if (!classroom_quiz($fresh, $quizId)) throw new InvalidArgumentException('Quiz is no longer available.');
        $check = $pdo->prepare('SELECT COUNT(*) FROM attempts WHERE classroom_id = ? AND quiz_id = ? AND student_id = ?'); $check->execute([$classroomId, $quizId, $studentId]);
        if ($check->fetchColumn()) throw new InvalidArgumentException('This student has already submitted an attempt.');
        $recent = $pdo->prepare('SELECT COUNT(*) FROM academic_reminders WHERE classroom_id = ? AND quiz_id = ? AND student_id = ? AND created_at >= ?');
        $recent->execute([$classroomId, $quizId, $studentId, date(DATE_ATOM, time() - 3600)]);
        if ($recent->fetchColumn()) throw new InvalidArgumentException('A reminder was already sent to this student within the last hour.');
        $pdo->prepare('INSERT INTO academic_reminders (classroom_id, quiz_id, student_id, teacher_id, body, created_at) VALUES (?, ?, ?, ?, ?, ?)')->execute([$classroomId, $quizId, $studentId, $user['id'], $body, now_iso()]);
        record_audit('quiz_reminder_sent', (int) $user['id'], $studentId); $pdo->commit();
        flash_set('success', 'Reminder delivered inside the student’s classroom.'); redirect('/QuizWeb/participants.php?classroom_id=' . $classroomId . '&quiz_id=' . $quizId);
    } catch (Throwable $ex) { if ($pdo->inTransaction()) $pdo->rollBack(); $error = $ex instanceof InvalidArgumentException ? $ex->getMessage() : 'Could not send the reminder. Please retry.'; }
}
$attempts = classroom_attempts($classroomId); $query = db()->prepare('SELECT * FROM quiz_runs WHERE classroom_id = ? AND quiz_id = ?'); $query->execute([$classroomId, $quizId]);
$allRows = participation_rows($classroom, $quiz, classroom_students($classroom), $attempts, $query->fetchAll());
$search = is_string($_GET['q'] ?? null) ? mb_strtolower(trim($_GET['q'])) : ''; $status = is_string($_GET['status'] ?? null) ? $_GET['status'] : '';
$filtered = array_values(array_filter($allRows, fn($row) => ($search === '' || str_contains(mb_strtolower($row['student']['name']), $search)) && ($status === '' || $status === $row['status'])));
usort($filtered, fn($a, $b) => $a['student']['name'] <=> $b['student']['name']); $page = page_records($filtered, 'page', 12);
render_header('Quiz Participants', 'gradebook-page academic-page', ['/QuizWeb/assets/css/gradebook.css', '/QuizWeb/assets/css/academic-grades.css']); ?>
<header class="page-heading"><div><span class="eyebrow"><?php echo esc($classroom['name']); ?></span><h1>Quiz participants</h1><p><?php echo esc($quiz['title']); ?> · <?php echo !empty($quiz['due_at']) ? 'Due ' . esc(format_date($quiz['due_at'])) : 'No deadline'; ?></p></div><a class="button button-secondary" href="/QuizWeb/classroom.php?id=<?php echo $classroomId; ?>">Back to Classroom</a></header>
<?php if ($error): ?><p class="inline-error" role="alert"><?php echo esc($error); ?></p><?php endif; ?>
<section class="glass panel academic-gradebook"><div class="academic-stat-grid"><?php foreach (['Enrolled' => count($allRows), 'Submitted' => count(array_filter($allRows, fn($r) => $r['completed'])), 'Taking quiz' => count(array_filter($allRows, fn($r) => $r['active'])), 'No submission' => count(array_filter($allRows, fn($r) => !$r['completed']))] as $label => $value): ?><article><strong><?php echo $value; ?></strong><span><?php echo esc($label); ?></span></article><?php endforeach; ?></div><p class="muted">Taking Quiz means an authenticated live run was active within the last two minutes. A student may be retaking an already submitted quiz.</p>
<form method="get" class="academic-filter-bar"><input type="hidden" name="classroom_id" value="<?php echo $classroomId; ?>"><input type="hidden" name="quiz_id" value="<?php echo $quizId; ?>"><label><span>Student</span><input type="search" name="q" value="<?php echo esc($search); ?>"></label><label><span>Participation</span><select name="status"><option value="">All students</option><?php foreach (['Completed', 'Not Taken', 'Taking Quiz', 'Overdue / Missing'] as $option): ?><option <?php echo $status === $option ? 'selected' : ''; ?>><?php echo esc($option); ?></option><?php endforeach; ?></select></label><button class="button button-secondary">Filter</button><a class="button button-secondary" href="<?php echo esc('/QuizWeb/participants.php?' . http_build_query($_GET)); ?>">Refresh</a></form>
<div class="academic-table-scroll"><table class="academic-table"><thead><tr><th>Student</th><th>Status</th><th>Latest score</th><th>Attempts</th><th>Last submission</th><th>Actions</th></tr></thead><tbody><?php foreach ($page['items'] as $row): ?><tr><th><?php echo esc($row['student']['name']); ?></th><td><span class="academic-status"><?php echo esc($row['status']); ?></span><?php if ($row['late']): ?><small>Late submission</small><?php endif; ?></td><td><?php echo $row['score'] === null ? '—' : esc($row['score'] . ' / ' . $row['max_score']); ?></td><td><?php echo $row['count']; ?></td><td><?php echo $row['submitted_at'] ? esc(format_date($row['submitted_at'])) : '—'; ?></td><td><button type="button" class="button button-secondary" data-open-grade="participant-<?php echo (int) $row['student']['id']; ?>"><?php echo $row['completed'] ? 'Attempt History' : 'Send Reminder'; ?></button></td></tr><?php endforeach; ?><?php if (!$filtered): ?><tr><td colspan="6" class="academic-empty">No students match your filters.</td></tr><?php endif; ?></tbody></table></div><?php render_pagination($page); ?></section>
<?php foreach ($page['items'] as $row): ?><dialog class="academic-drawer" id="participant-<?php echo (int) $row['student']['id']; ?>"><header><h2><?php echo esc($row['student']['name']); ?></h2><button class="academic-close" type="button" data-close-grade aria-label="Close participant details">×</button></header><div class="academic-drawer-body"><?php if ($row['attempts']): ?><h3>Attempt history</h3><?php foreach ($row['attempts'] as $attempt): ?><article class="academic-analysis-row"><span><?php echo esc($attempt['score'] . '/' . $attempt['max_score'] . ' · ' . format_date($attempt['played_at'])); ?></span><a class="button button-secondary" href="/QuizWeb/results.php?id=<?php echo (int) $attempt['id']; ?>">Review Answers</a></article><?php endforeach; ?><?php else: ?><form method="post" class="stack-form"><input type="hidden" name="csrf" value="<?php echo esc(form_csrf()); ?>"><input type="hidden" name="student_id" value="<?php echo (int) $row['student']['id']; ?>"><label><span>Classroom reminder</span><textarea name="body" maxlength="500" rows="4" required><?php echo esc('Please complete ' . $quiz['title'] . (!empty($quiz['due_at']) ? ' (due ' . format_date($quiz['due_at']) . ').' : '.')); ?></textarea></label><button class="button button-primary">Send Reminder</button><p class="muted">Delivered privately inside this classroom.</p></form><?php endif; ?></div></dialog><?php endforeach; ?>
<?php render_footer(['/QuizWeb/assets/js/academic-grades.js']); ?>
