const {JSDOM} = require('../data/qa/node_modules/jsdom');
const {execFileSync} = require('node:child_process');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const fixture = JSON.parse(execFileSync(process.env.PHP_BINARY || 'C:/xampppp/php/php.exe', ['tests/member_profile_fixture.php', '--image-attachments'], {encoding: 'utf8'}));
const tick = () => new Promise(resolve => setImmediate(resolve));
(async () => {
    const dom = new JSDOM(fixture.html, {url: 'http://localhost/QuizWeb/dashboard.php', runScripts: 'outside-only', pretendToBeVisual: true});
    const w = dom.window, d = w.document, intervals = [];
    const dock = d.querySelector('[data-messenger-dock]');
    const imageName = 'Screenshot-private.png';
    const sourceUrl = fixture.threads[0].messages[0].attachments[0].url;
    assert.equal(dock.querySelector('[data-chat-image-open]').textContent, '', 'Initial PHP render shows no image filename');
    assert(!dock.textContent.includes(imageName), 'Initial conversation and bubble hide the image filename');
    assert.equal(dock.querySelector('.chat-file-link').textContent, 'Lesson.pdf · 2 KB');
    w.matchMedia = () => ({matches: false});
    w.setInterval = fn => { intervals.push(fn); return intervals.length; };
    w.fetch = async () => ({ok: true, json: async () => ({threads: fixture.threads})});
    w.open = () => { throw new Error('Image viewing must not open tabs'); };
    w.HTMLDialogElement.prototype.showModal = function () { this.setAttribute('open', ''); };
    w.HTMLDialogElement.prototype.close = function () { this.removeAttribute('open'); this.dispatchEvent(new w.Event('close')); };
    w.eval(fs.readFileSync('assets/js/site.js', 'utf8'));
    // The initial thumbnail opens without waiting for a refresh.
    d.querySelector('.messenger-launcher').click();
    dock.querySelector('[data-chat-image-open] img').click();
    const dialog = d.querySelector('.chat-image-preview');
    assert(dialog.open, 'Clicking the thumbnail opens a modal in this page');
    assert(dock.classList.contains('is-open'));
    assert.equal(dialog.querySelector('img').src, `http://localhost${sourceUrl}&view=1`, 'Preview requests the authorized inline image');
    assert(!dialog.textContent.includes(imageName));
    assert.equal(d.activeElement, dialog.querySelector('.chat-image-preview-close'));
    const save = dialog.querySelector('[data-chat-image-save]');
    assert.equal(save.href, `http://localhost${sourceUrl}`);
    assert.equal(save.download, imageName, 'Save keeps the original download name');
    assert(!save.hasAttribute('target'), 'Saving needs no new tab');
    save.addEventListener('click', event => event.preventDefault()); // Inspect the native download action without jsdom navigation.
    save.click(); assert(dialog.open && dock.classList.contains('is-open'), 'Save does not close the preview or messenger');
    await tick(); await tick();
    assert(!dock.textContent.includes(imageName), 'Live polling also hides filenames');
    assert.equal(dock.querySelector('.messenger-group-copy > span').textContent, 'Shared an image');
    assert(!dock.querySelector('[data-chat-image-open]').hasAttribute('href'), 'An image is a preview control, not a download link');
    dialog.querySelector('img').dispatchEvent(new w.Event('load'));
    assert.equal(dialog.querySelector('[role="status"]').textContent, '');
    dialog.querySelector('.chat-image-preview-close').click();
    assert(!dialog.open && dock.classList.contains('is-open'));
    assert.equal(d.activeElement, dock.querySelector('[data-chat-image-open]'), 'Closing restores focus after polling replaced the thumbnail');
    assert(!dialog.querySelector('img').hasAttribute('src'));
    dock.querySelector('[data-chat-image-open]').click();
    dialog.dispatchEvent(new w.KeyboardEvent('keydown', {key: 'Escape', bubbles: true, cancelable: true}));
    assert(!dialog.open && dock.classList.contains('is-open'), 'Escape closes only the preview');
    dock.querySelector('[data-chat-image-open]').click();
    dialog.querySelector('img').dispatchEvent(new w.Event('error'));
    assert.match(dialog.querySelector('[role="status"]').textContent, /could not be loaded/);
    dialog.getBoundingClientRect = () => ({left: 10, right: 300, top: 10, bottom: 300});
    dialog.dispatchEvent(new w.MouseEvent('click', {clientX: 0, clientY: 0, bubbles: true}));
    assert(!dialog.open && dock.classList.contains('is-open'), 'Backdrop closes the preview while preserving the conversation');
    fixture.threads[0].messages[0].body = 'A new caption';
    await intervals[0](); await tick();
    assert.equal(dock.querySelector('.messenger-group-copy > span').textContent, 'A new caption');
    dock.querySelector('[data-chat-image-open]').click();
    assert.equal(d.querySelectorAll('.chat-image-preview').length, 1, 'Refreshed thumbnails reuse the preview');
    assert(dialog.open); dialog.close();
    assert(dock.querySelector('.chat-file-link').textContent.includes('Lesson.pdf'), 'Documents retain filenames and downloads');
    const bad = dock.querySelector('[data-chat-image-open]'); bad.dataset.imageUrl = 'https://outside.example/photo.png'; bad.click();
    assert(!dialog.open, 'Preview sources stay on the protected local file endpoint');
    dom.window.close();
    console.log('Initial/live image rendering, hidden filenames, inline modal preview, Save download, focus after refresh, Close/Escape/backdrop, load errors, captions, and document downloads passed.');
})().catch(error => { console.error(error); process.exitCode = 1; });
