const {JSDOM} = require('../data/qa/node_modules/jsdom');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const {execFileSync} = require('node:child_process');
const source = name => fs.readFileSync(`assets/js/${name}.js`, 'utf8');
const question = (points = 10, level = 'easy') => ({id: 1, prompt: 'Which answer?', options: ['Yes', 'No', 'Maybe', 'Other'], correct_index: 0, points, level});
function setup(quiz, preview = true, practice = false) {
    const php = process.env.PHP_BINARY || (process.platform === 'win32' ? 'C:/xampppp/php/php.exe' : 'php');
    const markup = execFileSync(php, ['tests/game_page_fixture.php', practice ? 'practice' : 'play'], {input: JSON.stringify(quiz), encoding: 'utf8'});
    const dom = new JSDOM(markup, {url: 'http://localhost/QuizWeb/', runScripts: 'outside-only', pretendToBeVisual: true});
    const w = dom.window, doc = w.document, root = doc.querySelector('[data-game-root]');
    root.dataset.quiz = JSON.stringify(quiz); root.dataset.isPreview = preview ? '1' : '0'; root.dataset.practiceMode = practice ? '1' : '0'; root.dataset.integrityUrl = '/QuizWeb/quiz_integrity.php';
    const submits = [], intervals = new Map(), delays = new Map(); let id = 0, fullscreen = 0;
    w.setInterval = fn => { intervals.set(++id, fn); return id; }; w.clearInterval = key => intervals.delete(key);
    w.setTimeout = fn => { delays.set(++id, fn); return id; }; w.clearTimeout = key => delays.delete(key);
    w.HTMLFormElement.prototype.submit = function() { submits.push(Object.fromEntries(new w.FormData(this))); };
    doc.documentElement.requestFullscreen = () => { fullscreen++; Object.defineProperty(doc, 'fullscreenElement', {value: doc.documentElement, configurable: true}); return Promise.resolve(); };
    w.fetch = async (_, options) => { assert.equal(options.body.get('action'), 'start', 'Only the security start event is expected'); return {ok: true, json: async () => ({warnings: 0, disqualified: false})}; };
    w.eval(source('game-experience')); w.eval(source('quiz-integrity'));
    w.eval(source(['flip_match','fill_blank','emoji_quiz'].includes(quiz.game_type) ? 'activity-game' : 'game'));
    const controls = doc.querySelector('[data-game-controls]');
    return {w, doc, root, submits, intervals, delays, controls, fullscreen: () => fullscreen, start: async () => { controls.querySelector('.button-primary').click(); await new Promise(resolve => setImmediate(resolve)); }, answer: index => doc.querySelectorAll('[data-answer-index]')[index].click(), next: () => controls.querySelector('.button-primary').click(), close: () => w.close()};
}
(async () => {
    for (const mode of ['standard','rocket_rush','treasure_dive','memory_flip','boss_battle']) {
        const a = setup({title: mode, game_type: mode, questions: [question(20), {...question(30), id: 2}]}, false);
        const briefing = a.root.querySelector('[data-game-briefing]');
        const instructions = a.root.querySelector('.game-instructions');
        assert(briefing && !briefing.hidden, 'Activity details are available before starting');
        assert(instructions.contains(a.doc.querySelector('.quiz-security-notice')), 'Full security rules remain accessible in instructions');
        assert(a.doc.querySelector('[data-game-security] .quiz-warning-count'), 'Warning status remains visible in the game header');
        briefing.open = true; instructions.open = true; a.root.querySelector('.mode-stage').scrollTop = 200;
        await a.start();
        assert(briefing.hidden && !briefing.open, 'Starting collapses and hides the introduction');
        assert(!instructions.open, 'Instructions collapse while remaining accessible during play');
        assert(a.root.closest('.game-shell').classList.contains('is-playing'));
        assert.equal(a.root.querySelector('.mode-stage').scrollTop, 0, 'Play starts at the top of the expanded stage');
        assert.equal(a.fullscreen(), 1, 'Live play retains the fullscreen gate');
        a.answer(0); a.answer(0);
        assert.equal(a.doc.querySelector('[data-score-value]').textContent, '20', 'Locked answers cannot award twice');
        assert.match(a.doc.querySelector('[data-answer-feedback]').textContent, /Correct! \+20 points/);
        if (['rocket_rush','treasure_dive'].includes(mode)) assert.equal(a.doc.querySelector('.game-journey progress').value, 50);
        if (mode === 'boss_battle') assert.equal(a.doc.querySelector('[data-boss-health]').style.width, '50%');
        a.next(); a.answer(1); assert.match(a.doc.querySelector('[data-answer-feedback]').textContent, /Correct answer: Yes/);
        assert.equal(a.doc.querySelector('[data-score-value]').textContent, '20');
        a.next(); assert.equal(a.submits.length, 0, 'Completion must precede submission');
        const view = a.controls.querySelector('.button-primary'); view.click(); view.click();
        assert.equal(a.submits.length, 1, 'Submit only once');
        assert(!('score' in a.submits[0]), 'Client does not send authoritative points');
        const answers = JSON.parse(a.submits[0].answers); assert.equal(answers[0], 0); assert.equal(answers[1], 1);
        a.close();
    }
    const time = setup({title: 'Timer', game_type: 'time_attack', questions: [question()]});
    await time.start(); const tick = [...time.intervals.values()][1];
    for (let i = 0; i < 6; i++) tick(); assert.equal(time.root.dataset.timerState, 'warning');
    for (let i = 0; i < 3; i++) tick(); assert.equal(time.root.dataset.timerState, 'urgent');
    for (let i = 0; i < 3; i++) tick(); assert.match(time.doc.querySelector('[data-answer-feedback]').textContent, /Time’s Up/);
    assert.equal(time.doc.querySelector('[data-score-value]').textContent, '0'); time.next(); assert.equal(time.submits.length, 0); time.close();
    const ladder = setup({title: 'Ladder', game_type: 'master_ladder', mastery_threshold: 75, questions: ['easy','medium','hard','master'].map((level, i) => ({...question(), id:i + 1, level}))});
    await ladder.start(); ladder.answer(0); assert.match(ladder.controls.textContent, /Unlock Medium/); assert.match(ladder.doc.querySelector('[data-ladder-level="1"]').textContent, /Unlocked/); ladder.next();
    assert.match(ladder.doc.querySelector('[data-ladder-level="1"]').textContent, /Current/);
    ladder.answer(1); assert.match(ladder.doc.querySelector('[data-question-helper]').textContent, /need 75%/); ladder.next(); assert.equal(ladder.submits.length, 0); ladder.close();
    for (const mode of ['fill_blank','emoji_quiz']) {
        const text = setup({title:'Text',game_type:mode,questions:[{id:1,prompt:'Clue',points:10}]}, false);
        await text.start(); text.next(); assert.match(text.doc.querySelector('.activity-review-row').textContent, /Unanswered/);
        text.doc.querySelector('.activity-review-row button').click(); text.doc.querySelector('input').value = 'Response'; text.next();
        assert.match(text.doc.querySelector('.activity-review-row').textContent, /Answered/);
        text.next(); assert.equal(text.submits.length,0); text.next(); text.next(); assert.equal(text.submits.length,1); text.close();
    }
    const match = setup({title:'Match',game_type:'flip_match',questions:[{id:1,prompt:'Term A',answer:'Definition A',points:10},{id:2,prompt:'Term B',answer:'Definition B',points:10}]});
    match.w.Math.random = () => .999; await match.start();
    const tiles = [...match.doc.querySelectorAll('.match-card')];
    tiles[0].click(); tiles[2].click(); tiles[1].click(); assert.equal(tiles[1].textContent, '?', 'Busy mismatch prevents third card');
    [...match.delays.values()].forEach(fn => fn()); assert.equal(tiles[0].textContent,'?');
    tiles[0].click(); tiles[1].click(); tiles[2].click(); tiles[3].click(); match.next();
    assert.equal(match.submits.length,0,'Matching preview never writes'); assert.match(match.doc.querySelector('[data-question-helper]').textContent,/20 \/ 20/); match.close();
    const imageData = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aC1sAAAAASUVORK5CYII=';
    const imageMatch = setup({title:'Image matching',game_type:'flip_match',questions:[{id:1,prompt:'First photo',answer:'First match',prompt_image:imageData,answer_image:imageData,points:10},{id:2,prompt:'Second term',answer:'Second definition',points:10}]});
    imageMatch.w.Math.random = () => .99; await imageMatch.start();
    const imageTiles = [...imageMatch.doc.querySelectorAll('.match-card')];
    assert.equal(imageMatch.doc.querySelectorAll('.match-card img').length,0,'Images stay hidden before flipping');
    imageTiles[0].click(); assert.equal(imageTiles[0].querySelector('img').alt,'First photo');
    imageTiles[2].click(); [...imageMatch.delays.values()].forEach(fn=>fn());
    assert.equal(imageTiles[0].querySelector('img'),null,'Mismatch hides image again');
    imageTiles[0].click(); imageTiles[1].click();
    assert(imageTiles[0].disabled && imageTiles[1].disabled); assert.equal(imageTiles[1].querySelector('img').src,imageData,'Image-to-image match remains revealed'); imageMatch.close();
    const crossword = setup({title:'Puzzle', game_type:'crossword', questions:[{id:1,prompt:'Animal',word_length:3,points:10}],crossword_layout:{cols:3,cells:[[1,1,1]],placements:[{question_id:1,row:0,col:0,direction:'across',number:1}]}},false);
    await crossword.start(); assert(!crossword.controls.textContent.includes('Answer Key'));
    crossword.doc.querySelector('[data-clue-tab="down"]').click();
    assert(!crossword.doc.querySelector('[data-clue-section="down"]').hidden);
    assert.match(crossword.doc.querySelector('[data-clue-section="down"]').textContent,/No down clues/);
    crossword.doc.querySelector('[data-clue-id]').click(); assert.match(crossword.doc.querySelector('[data-current-clue]').textContent,/Animal/);
    const cells = [...crossword.doc.querySelectorAll('.crossword-cell-input')]; cells.forEach((cell,i) => { cell.value='CAT'[i]; cell.dispatchEvent(new crossword.w.Event('input')); });
    assert.match(crossword.doc.querySelector('[data-question-points]').textContent,/1 \/ 1 words filled/);
    crossword.next(); assert.match(crossword.doc.querySelector('[data-question-points]').textContent,/after submission/); crossword.next();
    assert.equal(JSON.parse(crossword.submits[0].answers)[0],'CAT'); crossword.close();
    const crossingQuiz = {id: 3, title: 'Crossing words', game_type: 'crossword', questions: [
        {id: 2, prompt: 'Vehicle', word_length: 3, points: 20},
        {id: 1, prompt: 'Animal <em>clue</em>', word_length: 3, points: 10},
    ], crossword_layout: {cols: 3, cells: [[1,1,1],[1,0,0],[1,0,0]], placements: [
        {question_id: 1, row: 0, col: 0, direction: 'across', number: 1},
        {question_id: 2, row: 0, col: 0, direction: 'down', number: 1},
    ]}};
    const crossing = setup(crossingQuiz, false);
    let resize, disconnected = false;
    crossing.w.ResizeObserver = class { constructor(fn) { resize = fn; } observe() {} disconnect() { disconnected = true; } };
    await crossing.start();
    const select = selector => crossing.doc.querySelector(selector);
    const cell = (row, col) => select(`[data-row="${row}"][data-col="${col}"]`);
    const write = (row, col, letter) => { const input = cell(row, col); input.focus(); input.value = letter; input.dispatchEvent(new crossing.w.Event('input')); };
    assert(select('.crossword-footer').contains(crossing.controls), 'Submit stays in the footer and inside the security boundary');
    assert(select('.crossword-clues').contains(select('.game-instructions')), 'Instructions remain accessible inside the clue panel');
    assert(select('.game-instructions').contains(select('.quiz-security-notice')), 'Live security rules survive the layout change');
    assert.equal(select('.crossword-clue-prompt').innerHTML, 'Animal &lt;em&gt;clue&lt;/em&gt;', 'Clue text cannot inject markup');
    assert.equal(select('.crossword-clue-length').textContent, '3 letters');
    assert.equal(select('.crossword-cell-number').textContent, '1', 'Shared starts keep a simple number');
    assert.equal(crossing.doc.activeElement, cell(0,0), 'The first cell is ready to type');
    const board = select('.crossword-board-scroll');
    board.getBoundingClientRect = () => ({width: 500, height: 350}); resize();
    assert.equal(select('.crossword-grid').style.getPropertyValue('--crossword-cell-size'), '64px');
    assert(!board.classList.contains('crossword-board-overflow'), 'Small puzzles center within the available space');
    board.getBoundingClientRect = () => ({width: 110, height: 110}); resize();
    assert.equal(select('.crossword-grid').style.getPropertyValue('--crossword-cell-size'), '36px');
    assert(board.classList.contains('crossword-board-overflow'), 'A large puzzle remains scrollable without clipping its first cell');
    write(0,0,'c'); assert.equal(cell(0,0).value,'C'); assert.equal(crossing.doc.activeElement,cell(0,1));
    write(0,1,'A'); write(0,2,'T');
    assert.equal(select('[data-crossword-filled]').textContent,'1 / 2 words');
    assert.equal(select('[role="progressbar"]').getAttribute('aria-valuenow'),'1');
    assert.equal(crossing.doc.querySelectorAll('[data-word-dot].is-filled').length,1);
    select('[data-clue-tab="down"]').click();
    assert.equal(select('[data-clue-id="2"]').getAttribute('aria-pressed'),'true','Down selects a vertical word at the shared starting cell');
    write(0,0,'C'); assert.equal(crossing.doc.activeElement,cell(1,0),'Vertical typing advances downward');
    cell(1,0).dispatchEvent(new crossing.w.KeyboardEvent('keydown',{key:'Backspace',bubbles:true}));
    assert.equal(crossing.doc.activeElement,cell(0,0),'Backspace follows the selected down word');
    write(1,0,'A'); write(2,0,'R'); assert.equal(select('[data-crossword-filled]').textContent,'2 / 2 words');
    cell(2,0).value=''; cell(2,0).dispatchEvent(new crossing.w.Event('input'));
    assert.equal(select('[role="progressbar"]').getAttribute('aria-valuenow'),'1','Erasing a letter updates completion');
    write(2,0,'R'); crossing.next();
    assert(disconnected,'Finishing releases the grid resize observer');
    assert(!select('.crossword-footer') && !crossing.root.classList.contains('crossword-running'));
    assert(select('.question-stage').contains(crossing.controls),'Completion restores the shared controls');
    assert(crossing.root.contains(select('.game-instructions')),'Completion preserves instructions');
    assert.equal(crossing.submits.length,0,'The crossword keeps its confirmation before saving');
    crossing.next(); crossing.next();
    assert.equal(crossing.submits.length,1);
    assert.deepEqual(JSON.parse(crossing.submits[0].answers),['CAR','CAT'],'Submitted words follow question order, not clue order');
    assert(!('score' in crossing.submits[0]),'The new surface still leaves grading to the server'); crossing.close();
    const keyQuiz = JSON.parse(JSON.stringify(crossingQuiz));
    keyQuiz.questions[0].answer = 'CAR'; keyQuiz.questions[1].answer = 'CAT';
    keyQuiz.crossword_layout.cells = [['C','A','T'],['A',null,null],['R',null,null]];
    const keyPreview = setup(keyQuiz);
    await keyPreview.start();
    const keyCells = [...keyPreview.doc.querySelectorAll('.crossword-cell-input')];
    keyCells[0].value='X'; keyCells[0].dispatchEvent(new keyPreview.w.Event('input'));
    keyPreview.controls.querySelector('.button-secondary').click();
    assert(keyCells.every(input => input.readOnly)); assert.equal(keyCells[0].value,'C');
    keyPreview.controls.querySelector('.button-secondary').click();
    assert(keyCells.every(input => !input.readOnly)); assert.equal(keyCells[0].value,'X');
    assert(keyCells.slice(1).every(input => input.value===''),'Hiding the preview key restores the teacher\'s entries');
    keyPreview.controls.querySelector('.button-secondary').click(); keyPreview.next();
    assert.equal(keyPreview.doc.querySelector('[data-score-value]').textContent,'30');
    assert.match(keyPreview.doc.querySelector('[data-question-helper]').textContent,/Accuracy 100%/);
    assert.equal(keyPreview.submits.length,0,'Teacher answer keys and previews never save an attempt'); keyPreview.close();
    const practice = setup({title:'Practice', game_type:'time_attack',questions:[question()]},false,true);
    await practice.start(); practice.w.dispatchEvent(new practice.w.Event('blur'));
    assert.equal(practice.fullscreen(),0); assert(!practice.doc.querySelector('.quiz-integrity-dialog')); practice.close();
    console.log('Actual play/practice templates: expanded play state, collapsed briefing, accessible instructions, visible security status, locked answers, scoring, completion, submission, timer, mastery, written review, matching, crossword secrecy, preview isolation, and practice exemption passed.');
})().catch(error => { console.error(error); process.exitCode = 1; });
