const {JSDOM} = require('../data/qa/node_modules/jsdom');
const {execFileSync} = require('node:child_process');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const fixture = JSON.parse(execFileSync(process.env.PHP_BINARY || 'C:/xampppp/php/php.exe', ['tests/member_profile_fixture.php'], {encoding: 'utf8'}));
const tick = () => new Promise(resolve => setImmediate(resolve));
(async () => {
    const dom = new JSDOM(`<body>${fixture.html}</body>`, {url: 'http://localhost/QuizWeb/dashboard.php', runScripts: 'outside-only', pretendToBeVisual: true});
    const w = dom.window, d = w.document;
    const intervals = [], revoked = [];
    w.matchMedia = () => ({matches: false});
    w.setInterval = fn => { intervals.push(fn); return intervals.length; };
    w.fetch = async () => ({ok: true, json: async () => ({threads: fixture.threads})});
    w.URL.createObjectURL = () => 'blob:photo-preview';
    w.URL.revokeObjectURL = url => revoked.push(url);
    w.eval(fs.readFileSync('assets/js/site.js', 'utf8'));
    await tick(); await tick();
    d.querySelector('.messenger-launcher').click();
    const thread = d.querySelector('[data-chat-id="1"][data-messenger-thread]');
    const toggle = thread.querySelector('[data-chat-members-toggle]'), panel = thread.querySelector('[data-chat-members-panel]');
    toggle.click();
    assert(!panel.hidden); assert.equal(toggle.getAttribute('aria-expanded'), 'true');
    assert.equal(panel.querySelectorAll('li').length, 2);
    assert(panel.textContent.includes('Student (You)'));
    assert.equal(d.activeElement, panel.querySelector('[data-chat-members-close]'));
    panel.querySelector('[data-chat-members-close]').dispatchEvent(new w.KeyboardEvent('keydown', {key: 'Escape', bubbles: true}));
    assert(panel.hidden); assert(d.querySelector('[data-messenger-dock]').classList.contains('is-open'));
    assert.equal(d.activeElement, toggle);
    toggle.click(); d.querySelector('[data-messenger-target="messenger-thread-2"]').click();
    assert(panel.hidden); assert.equal(toggle.getAttribute('aria-expanded'), 'false');
    // Roster changes must refresh even when messages are unchanged.
    fixture.threads[0].members.push({id: 7, name: '<script>Private</script>', role: 'student', avatar_url: 'https://untrusted.example/avatar'});
    await intervals[0](); await tick();
    assert.equal(thread.querySelector('[data-chat-member-count]').textContent, '3');
    assert.equal(panel.querySelectorAll('li').length, 3);
    assert(panel.textContent.includes('<script>Private</script>'));
    assert(!panel.querySelector('script')); assert.equal(panel.querySelectorAll('img').length, 1);
    const image = panel.querySelector('img'); image.dispatchEvent(new w.Event('error')); assert(!panel.querySelector('img'));
    const form = d.querySelector('[data-profile-photo-form]'), input = form.querySelector('[data-profile-photo-input]');
    Object.defineProperty(input, 'files', {value: [new w.File(['image'], 'photo.png', {type: 'image/png'})], configurable: true});
    input.dispatchEvent(new w.Event('change'));
    assert.equal(form.querySelector('[data-profile-photo-preview] img').getAttribute('src'), 'blob:photo-preview');
    Object.defineProperty(input, 'files', {value: [new w.File(['svg'], 'unsafe.svg', {type: 'image/svg+xml'})], configurable: true});
    input.dispatchEvent(new w.Event('change'));
    assert(form.querySelector('[data-profile-photo-status]').textContent.includes('2 MB'));
    assert(form.querySelector('[data-profile-photo-preview] img').getAttribute('src').startsWith('/QuizWeb/profile_photo.php'));
    assert(revoked.includes('blob:photo-preview'));
    Object.defineProperty(input, 'files', {value: [], configurable: true});
    const event = new w.SubmitEvent('submit', {bubbles: true, cancelable: true, submitter: form.querySelector('[value="photo_upload"]')});
    form.dispatchEvent(event); assert(event.defaultPrevented);
    dom.window.close();
    console.log('Member list toggle/focus/Escape, class switching, refreshed rosters, safe avatars/names, photo preview, invalid-file reset, and empty-upload prevention passed.');
})().catch(error => { console.error(error); process.exitCode = 1; });
