<?php
// --database creates and removes its own randomly named database; never uses quizweb.
$schema = file_get_contents(__DIR__ . '/../database/schema.mysql.sql');
function mysql_check(bool $condition, string $message): void {
    if (!$condition) throw new RuntimeException($message);
}
foreach (['users', 'classrooms', 'attempts', 'audit_logs', 'gradebooks', 'grade_changes'] as $table) {
    mysql_check(str_contains($schema, 'CREATE TABLE IF NOT EXISTS ' . $table), 'Missing table: ' . $table);
}
mysql_check(substr_count($schema, 'FOREIGN KEY') === 4, 'All four foreign keys are required.');
mysql_check(!preg_match('/JSONB|ON CONFLICT|GENERATED BY DEFAULT|DROP TABLE/i', $schema), 'Incompatible or destructive SQL.');
mysql_check(str_contains($schema, 'WHERE NOT EXISTS'), 'Sample import must preserve existing accounts.');
if (!in_array('--database', $argv, true)) {
    echo "MySQL schema checks passed. Use --database for isolated live MySQL/MariaDB checks.\n";
    exit;
}
session_save_path(sys_get_temp_dir());
putenv('QUIZWEB_DB_DRIVER=mysql');
$testName = 'quizweb_test_' . bin2hex(random_bytes(8));
putenv('QUIZWEB_DB_NAME=' . $testName);
require_once __DIR__ . '/../includes/app.php';
$server = new PDO(sprintf('mysql:host=%s;port=%s;charset=utf8mb4', DB_HOST, DB_PORT), DB_USER, DB_PASS, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
$server->exec('CREATE DATABASE ' . $testName . ' CHARACTER SET utf8mb4 COLLATE utf8mb4_bin');
try {
    $pdo = new PDO(database_dsn(), DB_USER, DB_PASS, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]);
    ensure_database_schema($pdo);
    mysql_check((int) $pdo->query('SELECT COUNT(*) FROM users')->fetchColumn() === 0, 'Web startup must not seed accounts.');
    $pdo->exec($schema);
    mysql_check((int) $pdo->query('SELECT COUNT(*) FROM audit_logs')->fetchColumn() === 1, 'Admin import audit missing.');
    $pdo->exec("UPDATE users SET password = 'rotated', account_status = 'suspended' WHERE email = 'admin@chalk.local'");
    $pdo->exec($schema);
    mysql_check($pdo->query("SELECT password FROM users WHERE email = 'admin@chalk.local'")->fetchColumn() === 'rotated', 'Repeat import changed credentials.');
    mysql_check((int) $pdo->query('SELECT COUNT(*) FROM audit_logs')->fetchColumn() === 1, 'Repeat import duplicated audit.');
    mysql_check(table_has_column($pdo, 'users', 'profile'), 'MySQL column inspection failed.');
    $teacher = ['id' => 5, 'name' => 'Teacher', 'email' => 'teacher@example.test', 'password' => password_hash('Test123!', PASSWORD_DEFAULT), 'role' => 'teacher', 'created_at' => now_iso(), 'profile' => ['note' => 'Unicode 📚']];
    $student = array_replace($teacher, ['id' => 6, 'name' => 'Student', 'email' => 'student@example.test', 'role' => 'student']);
    insert_user_record($pdo, $teacher);
    insert_user_record($pdo, $student);
    $teacher['name'] = 'Updated teacher';
    insert_user_record($pdo, $teacher);
    mysql_check($pdo->query('SELECT name FROM users WHERE id = 5')->fetchColumn() === 'Updated teacher', 'User update failed.');
    try {
        insert_user_record($pdo, array_replace($teacher, ['id' => 7]));
        throw new RuntimeException('Duplicate email silently changed another account.');
    } catch (PDOException $expected) {}
    $class = ['id' => 1, 'teacher_id' => 5, 'student_ids' => [6], 'name' => 'Test class', 'subject' => 'Science', 'description' => '', 'code' => 'MYSQLTEST', 'quizzes' => [], 'announcements' => [], 'chat_messages' => [['body' => 'Hello 📚']], 'created_at' => now_iso(), 'updated_at' => now_iso()];
    insert_classroom_record($pdo, $class);
    insert_classroom_record($pdo, $class);
    $stored = hydrate_classroom($pdo->query('SELECT * FROM classrooms WHERE id = 1')->fetch());
    mysql_check($stored['chat_messages'] === $class['chat_messages'], 'JSON/Unicode roundtrip failed.');
    $config = ['categories' => [['id' => 'quiz', 'name' => 'Quizzes', 'weight' => 100]], 'scale' => [['min' => 0, 'label' => 'Recorded']], 'passing' => 75, 'missing_policy' => 'exclude'];
    grading_mutate($pdo, 1, $teacher, 'config', ['revision' => '0', 'config' => $config]);
    $quiz = ['id' => 1, 'title' => 'Original quiz', 'game_type' => 'standard', 'created_at' => now_iso(), 'questions' => [['id' => 1, 'prompt' => 'Question', 'answer' => 'Yes', 'points' => 10]], 'grade_category_id' => 'quiz', 'grade_max_score' => 100, 'grade_attempt_policy' => 'highest'];
    persist_builder_quiz($pdo, 1, 5, $quiz, true);
    $attempt = ['id' => 1, 'student_id' => 6, 'classroom_id' => 1, 'quiz_id' => 1, 'quiz_title' => $quiz['title'], 'game_type' => 'standard', 'answers' => [], 'score' => 8, 'max_score' => 10, 'elapsed_seconds' => 5, 'played_at' => now_iso()];
    insert_attempt_record($pdo, $attempt);
    insert_attempt_record($pdo, $attempt);
    $quiz['title'] = 'Edited quiz';
    persist_builder_quiz($pdo, 1, 5, $quiz, false);
    $storedAttempt = hydrate_attempt($pdo->query('SELECT * FROM attempts WHERE id = 1')->fetch());
    mysql_check($storedAttempt['answers']['_quiz_snapshot']['title'] === 'Original quiz', 'Historical quiz snapshot lost.');
    $book = grading_load($pdo, 1);
    grading_mutate($pdo, 1, $teacher, 'publish', ['revision' => (string) $book['revision'], 'confirm' => 'yes']);
    mysql_check(grading_load($pdo, 1)['published']['students'][6]['overall'] == 80, 'Published score incorrect.');
    $pdo->beginTransaction();
    insert_classroom_record($pdo, array_replace($class, ['name' => 'Must roll back']));
    $pdo->rollBack();
    mysql_check($pdo->query('SELECT name FROM classrooms WHERE id = 1')->fetchColumn() === 'Test class', 'Transaction rollback failed.');
    try {
        $pdo->exec('DELETE FROM classrooms WHERE id = 1');
        throw new RuntimeException('Gradebook foreign key did not restrict deletion.');
    } catch (PDOException $expected) {}
    echo "Live MySQL/MariaDB import/reimport, credential preservation, JSON, user/class/attempt saves, duplicate-email rejection, quiz snapshots, grade publication, rollback, and foreign keys passed.\n";
} finally {
    if (isset($pdo) && $pdo->inTransaction()) $pdo->rollBack();
    $pdo = null;
    $server->exec('DROP DATABASE ' . $testName);
}
