-- CHALK: one complete PostgreSQL setup file.
-- Create/select the quizweb database, then execute this file in pgAdmin's Query Tool
-- or run: psql -h 127.0.0.1 -U YOUR_USER -d quizweb -v ON_ERROR_STOP=1 -f database/schema.sql
-- Web requests execute the schema section only. Render's deployment bootstrap
-- explicitly imports the final demo-account section into Render PostgreSQL.


-- USERS: accounts, roles, status, and profile
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(190) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at VARCHAR(40) NOT NULL
);

-- CLASSROOMS: quizzes, enrollments, announcements, and chat are JSONB
CREATE TABLE IF NOT EXISTS classrooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT NOT NULL,
    name VARCHAR(190) NOT NULL,
    subject VARCHAR(190) NOT NULL,
    description TEXT NOT NULL,
    code VARCHAR(20) NOT NULL UNIQUE,
    student_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    quizzes JSONB NOT NULL DEFAULT '[]'::jsonb,
    announcements JSONB NOT NULL DEFAULT '[]'::jsonb,
    chat_messages JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at VARCHAR(40) NOT NULL,
    updated_at VARCHAR(40) NOT NULL
);

-- ATTEMPTS: scores, submitted answers, and historical quiz snapshots
CREATE TABLE IF NOT EXISTS attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    classroom_id BIGINT NOT NULL,
    quiz_id BIGINT NOT NULL,
    quiz_title VARCHAR(255) NOT NULL,
    game_type VARCHAR(100) NOT NULL,
    answers JSONB NOT NULL DEFAULT '[]'::jsonb,
    score INT NOT NULL,
    max_score INT NOT NULL,
    elapsed_seconds INT NOT NULL,
    played_at VARCHAR(40) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_classrooms_teacher_id ON classrooms (teacher_id);
CREATE INDEX IF NOT EXISTS idx_attempts_student_id ON attempts (student_id);
CREATE INDEX IF NOT EXISTS idx_attempts_classroom_id ON attempts (classroom_id);
CREATE INDEX IF NOT EXISTS idx_attempts_quiz_id ON attempts (quiz_id);

-- LEGACY UPGRADES: retain existing records and add missing columns only
ALTER TABLE users ADD COLUMN IF NOT EXISTS account_status VARCHAR(20) NOT NULL DEFAULT 'active';
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE classrooms ADD COLUMN IF NOT EXISTS chat_messages JSONB NOT NULL DEFAULT '[]'::jsonb;

-- AUDIT LOGS: account and operational events
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT,
    target_id BIGINT,
    action VARCHAR(80) NOT NULL,
    occurred_at VARCHAR(40) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action, id);

-- GRADEBOOKS: classroom grading configuration and published results
CREATE TABLE IF NOT EXISTS gradebooks (
    classroom_id BIGINT PRIMARY KEY REFERENCES classrooms(id) ON DELETE RESTRICT,
    data JSONB NOT NULL,
    updated_at VARCHAR(40) NOT NULL
);

-- GRADE CHANGES: grading audit history
CREATE TABLE IF NOT EXISTS grade_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classroom_id BIGINT NOT NULL REFERENCES gradebooks(classroom_id) ON DELETE RESTRICT,
    student_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    item_id VARCHAR(80),
    actor_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    action VARCHAR(80) NOT NULL,
    previous_value JSONB,
    new_value JSONB,
    created_at VARCHAR(40) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_grade_changes_classroom ON grade_changes(classroom_id, id);

-- Uploaded attachment bytes persist independently of the web container.
CREATE TABLE IF NOT EXISTS uploaded_files (
    scope VARCHAR(20) NOT NULL,
    stored_name VARCHAR(100) NOT NULL,
    data TEXT NOT NULL,
    PRIMARY KEY (scope, stored_name)
);

CREATE TABLE IF NOT EXISTS classroom_academics (classroom_id BIGINT PRIMARY KEY, data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS academic_settings (id VARCHAR(40) PRIMARY KEY, data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS quiz_runs (
    run_token VARCHAR(48) PRIMARY KEY, classroom_id BIGINT NOT NULL, quiz_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL, started_at VARCHAR(40) NOT NULL, last_seen VARCHAR(40) NOT NULL,
    completed_at VARCHAR(40), attempt_id BIGINT
);
CREATE INDEX IF NOT EXISTS idx_quiz_runs_classroom ON quiz_runs (classroom_id, quiz_id, student_id);

CREATE TABLE IF NOT EXISTS academic_reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, classroom_id BIGINT NOT NULL,
    quiz_id BIGINT NOT NULL, student_id BIGINT NOT NULL, teacher_id BIGINT NOT NULL,
    body TEXT NOT NULL, created_at VARCHAR(40) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_academic_reminders_student ON academic_reminders (classroom_id, student_id);

-- DEMO ADMIN: explicit import only
-- Sample administrator: admin@chalk.local / ChalkAdmin!2026
-- PHP password_verify-compatible bcrypt hash; existing emails are never reset.
-- Allocate above existing manually assigned IDs, which the app uses for users.
BEGIN;
LOCK TABLE users IN EXCLUSIVE MODE;
WITH created_admin AS (
    INSERT INTO users (id, name, email, password, role, created_at, profile, account_status)
    SELECT COALESCE(MAX(id), 0) + 1, 'Administrator', 'admin@chalk.local',
           '$2y$10$x/Z24ak.NUHsnwh8n9A/V.1igvVSEOp.HREJmUwIJvWF/btZ3a4T.',
           'admin', CURRENT_TIMESTAMP::text, '{}'::jsonb, 'active'
    FROM users
    WHERE true
    ON CONFLICT (email) DO NOTHING
    RETURNING id
)
INSERT INTO audit_logs (actor_id, target_id, action, occurred_at)
SELECT id, id, 'admin_created', CURRENT_TIMESTAMP::text FROM created_admin;
COMMIT;

-- TEST CLASSROOM: one teacher and two enrolled students, explicit import only.
-- All three accounts use password ChalkAdmin!2026. Reimports preserve credentials.
BEGIN;
LOCK TABLE users, classrooms IN EXCLUSIVE MODE;
INSERT INTO users (id, name, email, password, role, created_at, profile, account_status)
SELECT (SELECT COALESCE(MAX(id), 0) FROM users) + ROW_NUMBER() OVER (ORDER BY seed.email),
       seed.name, seed.email,
       '$2y$10$x/Z24ak.NUHsnwh8n9A/V.1igvVSEOp.HREJmUwIJvWF/btZ3a4T.',
       seed.role, CURRENT_TIMESTAMP::text, '{}'::jsonb, 'active'
FROM (VALUES
    ('Test Teacher', 'teacher@chalk.test', 'teacher'),
    ('Test Student One', 'student1@chalk.test', 'student'),
    ('Test Student Two', 'student2@chalk.test', 'student')
) AS seed(name, email, role)
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = seed.email);

INSERT INTO classrooms (id, teacher_id, name, subject, description, code,
                        student_ids, quizzes, announcements, chat_messages, created_at, updated_at)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM classrooms), teacher.id,
       'Test Classroom', 'General Education', 'Shared classroom for testing teacher and student logins.',
       'TESTCLASS', jsonb_build_array(student1.id, student2.id),
       '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, CURRENT_TIMESTAMP::text, CURRENT_TIMESTAMP::text
FROM users teacher, users student1, users student2
WHERE teacher.email = 'teacher@chalk.test' AND teacher.role = 'teacher'
  AND student1.email = 'student1@chalk.test' AND student1.role = 'student'
  AND student2.email = 'student2@chalk.test' AND student2.role = 'student'
ON CONFLICT (code) DO NOTHING;
COMMIT;

-- Give the test classroom an editable Balanced grading structure.
INSERT INTO gradebooks (classroom_id, data, updated_at)
SELECT classroom.id, '{"config":{"method":"weighted_categories","category_method":"points","categories":[{"id":"quiz","name":"Quizzes","weight":30},{"id":"work","name":"Assignments / Projects","weight":30},{"id":"exam","name":"Exams","weight":40}],"scale":[{"min":0,"label":"Below passing"},{"min":75,"label":"Passed"},{"min":90,"label":"Excellent"}],"passing":75,"missing_policy":"exclude","periods":[{"id":"prelim","name":"Prelim","weight":30},{"id":"midterm","name":"Midterm","weight":30},{"id":"finals","name":"Finals","weight":40}]},"items":{},"scores":{},"overrides":{},"revision":0,"next_item_id":1,"published":null}'::jsonb, CURRENT_TIMESTAMP::text
FROM classrooms classroom JOIN users teacher ON teacher.id = classroom.teacher_id
WHERE classroom.code = 'TESTCLASS' AND teacher.email = 'teacher@chalk.test' AND teacher.role = 'teacher'
ON CONFLICT (classroom_id) DO NOTHING;

INSERT INTO classroom_academics (classroom_id, data)
SELECT classroom.id, json_build_object('subject_code', 'GEN101', 'section', 'Test Section',
    'academic_year', EXTRACT(YEAR FROM CURRENT_DATE)::int::text || '–' || (EXTRACT(YEAR FROM CURRENT_DATE)::int + 1)::text,
    'semester', 'First Semester', 'credit_units', 3, 'required', true)::text
FROM classrooms classroom JOIN users teacher ON teacher.id = classroom.teacher_id
WHERE classroom.code = 'TESTCLASS' AND teacher.email = 'teacher@chalk.test'
ON CONFLICT (classroom_id) DO NOTHING;
