-- CHALK: one complete PostgreSQL setup file.
-- Create/select the quizweb database, then execute this file in pgAdmin's Query Tool
-- or run: psql -h 127.0.0.1 -U YOUR_USER -d quizweb -v ON_ERROR_STOP=1 -f database/schema.sql
-- Web requests execute the schema section only. Render's deployment bootstrap
-- explicitly imports the final demo-account section into Render PostgreSQL.


-- USERS: accounts, roles, status, and profile
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(190) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at VARCHAR(40) NOT NULL
);

-- CLASSROOMS: quizzes, enrollments, announcements, and chat are JSONB
CREATE TABLE IF NOT EXISTS classrooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT NOT NULL,
    name VARCHAR(190) NOT NULL,
    subject VARCHAR(190) NOT NULL,
    description TEXT NOT NULL,
    code VARCHAR(20) NOT NULL UNIQUE,
    student_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    quizzes JSONB NOT NULL DEFAULT '[]'::jsonb,
    announcements JSONB NOT NULL DEFAULT '[]'::jsonb,
    chat_messages JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at VARCHAR(40) NOT NULL,
    updated_at VARCHAR(40) NOT NULL
);

-- ATTEMPTS: scores, submitted answers, and historical quiz snapshots
CREATE TABLE IF NOT EXISTS attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    classroom_id BIGINT NOT NULL,
    quiz_id BIGINT NOT NULL,
    quiz_title VARCHAR(255) NOT NULL,
    game_type VARCHAR(100) NOT NULL,
    answers JSONB NOT NULL DEFAULT '[]'::jsonb,
    score INT NOT NULL,
    max_score INT NOT NULL,
    elapsed_seconds INT NOT NULL,
    played_at VARCHAR(40) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_classrooms_teacher_id ON classrooms (teacher_id);
CREATE INDEX IF NOT EXISTS idx_attempts_student_id ON attempts (student_id);
CREATE INDEX IF NOT EXISTS idx_attempts_classroom_id ON attempts (classroom_id);
CREATE INDEX IF NOT EXISTS idx_attempts_quiz_id ON attempts (quiz_id);

-- LEGACY UPGRADES: retain existing records and add missing columns only
ALTER TABLE users ADD COLUMN IF NOT EXISTS account_status VARCHAR(20) NOT NULL DEFAULT 'active';
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE classrooms ADD COLUMN IF NOT EXISTS chat_messages JSONB NOT NULL DEFAULT '[]'::jsonb;

-- AUDIT LOGS: account and operational events
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT,
    target_id BIGINT,
    action VARCHAR(80) NOT NULL,
    occurred_at VARCHAR(40) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action, id);

-- GRADEBOOKS: classroom grading configuration and published results
CREATE TABLE IF NOT EXISTS gradebooks (
    classroom_id BIGINT PRIMARY KEY REFERENCES classrooms(id) ON DELETE RESTRICT,
    data JSONB NOT NULL,
    updated_at VARCHAR(40) NOT NULL
);

-- GRADE CHANGES: grading audit history
CREATE TABLE IF NOT EXISTS grade_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classroom_id BIGINT NOT NULL REFERENCES gradebooks(classroom_id) ON DELETE RESTRICT,
    student_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    item_id VARCHAR(80),
    actor_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    action VARCHAR(80) NOT NULL,
    previous_value JSONB,
    new_value JSONB,
    created_at VARCHAR(40) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_grade_changes_classroom ON grade_changes(classroom_id, id);

-- DEMO ADMIN: explicit import only
-- Sample administrator: admin@chalk.local / ChalkAdmin!2026
-- PHP password_verify-compatible bcrypt hash; existing emails are never reset.
-- Allocate above existing manually assigned IDs, which the app uses for users.
BEGIN;
LOCK TABLE users IN EXCLUSIVE MODE;
WITH created_admin AS (
    INSERT INTO users (id, name, email, password, role, created_at, profile, account_status)
    SELECT COALESCE(MAX(id), 0) + 1, 'Administrator', 'admin@chalk.local',
           '$2y$10$x/Z24ak.NUHsnwh8n9A/V.1igvVSEOp.HREJmUwIJvWF/btZ3a4T.',
           'admin', CURRENT_TIMESTAMP::text, '{}'::jsonb, 'active'
    FROM users
    WHERE true
    ON CONFLICT (email) DO NOTHING
    RETURNING id
)
INSERT INTO audit_logs (actor_id, target_id, action, occurred_at)
SELECT id, id, 'admin_created', CURRENT_TIMESTAMP::text FROM created_admin;
COMMIT;
