<?php
require_once dirname(__DIR__, 3) . '/includes/layout.php';
require_once dirname(__DIR__, 3) . '/includes/grading_ui.php';
$user = require_role('teacher');
$classroomId = (int) ($_GET['classroom_id'] ?? 0);
$classroom = find_classroom($classroomId);
if (!$classroom || (int) $classroom['teacher_id'] !== (int) $user['id']) { http_response_code(403); exit('Gradebook access denied.'); }
$GLOBALS['quizweb_current_classroom_id'] = $classroomId;
$views = ['overview' => 'Gradebook', 'items' => 'Activities', 'setup' => 'Grading structure', 'analytics' => 'Analytics', 'audit' => 'Grade history'];
$view = is_string($_GET['view'] ?? null) ? $_GET['view'] : 'overview';
if (!isset($views[$view]) && !in_array($view, ['student', 'entry'], true)) $view = 'overview';
$error = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    require_form_csrf();
    $action = is_string($_POST['action'] ?? null) ? $_POST['action'] : '';
    $input = $_POST;
    if ($action === 'config') $input['config'] = is_string($_POST['config_payload'] ?? null) && strlen($_POST['config_payload']) <= 20000 ? json_decode($_POST['config_payload'], true) : null;
    try {
        grading_mutate(db(), $classroomId, $user, $action, $input);
        flash_set('success', $action === 'publish' ? 'Grade release published to enrolled students.' : 'Gradebook changes saved.');
        $params = ['classroom_id' => $classroomId, 'view' => $view];
        foreach (['student_id', 'item_id', 'page'] as $key) if (isset($_GET[$key]) && is_scalar($_GET[$key])) $params[$key] = $_GET[$key];
        redirect('/QuizWeb/gradebook.php?' . http_build_query($params));
    } catch (InvalidArgumentException $exception) { $error = $exception->getMessage(); }
    catch (Throwable $exception) { error_log('Gradebook save failed: ' . $exception->getMessage()); $error = 'Could not save grades. Your entered values are still here. Please retry.'; }
}
$book = grading_load(db(), $classroomId);
$select = db()->prepare('SELECT id, name, email FROM users WHERE id IN (SELECT CAST(value AS BIGINT) FROM jsonb_array_elements_text((SELECT student_ids FROM classrooms WHERE id = ?))) ORDER BY name, id');
$select->execute([$classroomId]); $students = $select->fetchAll();
$select = db()->prepare('SELECT * FROM attempts WHERE classroom_id = ? ORDER BY id'); $select->execute([$classroomId]); $attempts = array_map('hydrate_attempt', $select->fetchAll());
$rows = [];
if ($book['config']) foreach ($students as $student) $rows[(int) $student['id']] = grading_calculate($book, (int) $student['id'], $attempts);
$studentId = (int) ($_GET['student_id'] ?? 0);
if ($view === 'student' && !isset($rows[$studentId])) { http_response_code(404); exit('Enrolled student not found.'); }
$itemId = is_string($_GET['item_id'] ?? null) ? $_GET['item_id'] : '';
$item = $book['items'][$itemId] ?? null;
if ($view === 'entry' && (!$item || $item['source'] !== 'manual' || !empty($item['archived']))) { http_response_code(404); exit('Active manual activity not found.'); }
$url = '/QuizWeb/gradebook.php?classroom_id=' . $classroomId;
render_header('Gradebook', 'gradebook-page');
?>
<header class="page-heading"><div><span class="eyebrow"><?php echo esc($classroom['name']); ?> · Teacher gradebook</span><h1><?php echo esc($views[$view] ?? ($view === 'entry' ? 'Enter scores' : 'Student breakdown')); ?></h1><p>Draft calculations use saved scores. Students see their own published release.</p></div><a class="button button-secondary" href="/QuizWeb/classroom.php?id=<?php echo $classroomId; ?>">Back to Classroom</a></header>
<nav class="classroom-tabs" aria-label="Gradebook sections"><?php foreach ($views as $key => $label): ?><a href="<?php echo esc($url . '&view=' . $key); ?>" <?php echo $key === $view ? 'class="is-active" aria-current="page"' : ''; ?>><?php echo esc($label); ?></a><?php endforeach; ?></nav>
<?php if ($error): ?><p class="inline-error" role="alert"><?php echo esc($error); ?></p><?php endif; ?>
<?php if (!$book['config'] && $view !== 'setup'): ?>
<section class="glass panel empty-state"><h2>Set up classroom grading</h2><p>Choose your categories, weights, passing grade, and scale before assigning graded activities.</p><a class="button button-primary" href="<?php echo esc($url . '&view=setup'); ?>">Set Up Grading</a></section>
<?php elseif ($view === 'setup'): ?>
<section class="glass panel">
    <form method="post" id="grading-setup" class="stack-form" novalidate>
        <?php render_grade_form_fields($book); ?><input type="hidden" name="action" value="config"><input type="hidden" name="config_payload" id="grading-config-payload">
        <nav class="builder-steps" aria-label="Grading setup steps"><?php foreach (['Categories', 'Weights', 'Grade Scale', 'Review'] as $index => $label): ?><button type="button" data-grading-step="<?php echo $index; ?>"><?php echo ($index + 1) . '. ' . esc($label); ?></button><?php endforeach; ?></nav>
        <p id="grading-setup-status" role="status" aria-live="polite"></p>
        <section data-grading-panel="0"><h2>Your grading categories</h2><p>Rename and reorder categories. Categories used by active items must be reassigned or archived before removal.</p><div id="grading-categories"></div><button type="button" class="button button-secondary" id="add-grading-category">Add Category</button></section>
        <section data-grading-panel="1" hidden><h2>Category weights</h2><div id="grading-weights"></div><p id="grading-weight-total" role="status"></p><progress id="grading-weight-progress" max="100" value="0" aria-label="Configured category weight"></progress><p>Category calculation: earned points ÷ possible points × 100. Items with larger maximum scores have proportionally more influence.</p></section>
        <section data-grading-panel="2" hidden><h2>Grade scale and rules</h2><label><span>Passing grade (%)</span><input name="passing" type="number" min="0" max="100" step="0.01" value="<?php echo esc((string) ($book['config']['passing'] ?? 75)); ?>"></label>
        <label><span>Blank / missing scores</span><select name="missing_policy"><option value="exclude">Exclude ungraded scores; normalize available category weights</option><option value="zero" <?php echo ($book['config']['missing_policy'] ?? '') === 'zero' ? 'selected' : ''; ?>>Count assigned missing scores as zero</option></select></label>
        <p>Each band starts at its minimum and continues up to the next minimum. The first band must start at 0; the last includes 100.</p><div id="grading-scale"></div><button type="button" class="button button-secondary" id="add-grading-band">Add Scale Band</button></section>
        <section data-grading-panel="3" hidden><h2>Review the formula</h2><div id="grading-setup-review"></div><button type="submit" class="button button-primary">Save Grading Structure</button><p>Saving changes the draft calculation. Publish a release to update student grades.</p></section>
        <div class="action-row builder-toolbar"><button type="button" class="button button-secondary" id="grading-previous">Previous</button><button type="button" class="button button-primary" id="grading-next">Next</button></div>
    </form>
</section>
<?php $configSeed = $book['config'] ?? ['categories' => [], 'scale' => [['min' => 0, 'label' => 'Below passing'], ['min' => 75, 'label' => 'Passed']], 'passing' => 75, 'missing_policy' => 'exclude']; if ($error && isset($input['config']) && is_array($input['config'])) $configSeed = $input['config']; ?>
<script>window.gradingConfigSeed = <?php echo json_encode($configSeed, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT); ?>; window.gradingPostedDraft = <?php echo $error ? 'true' : 'false'; ?>;</script>
<?php elseif ($view === 'overview'): ?>
<section class="glass panel">
    <details class="grade-filters"><summary>Search &amp; filters</summary><form method="get" class="action-row"><input type="hidden" name="classroom_id" value="<?php echo $classroomId; ?>"><label><span>Student search</span><input type="search" name="q" value="<?php echo esc(is_string($_GET['q'] ?? null) ? $_GET['q'] : ''); ?>"></label><label><span>Category</span><select name="category_id"><option value="">All categories</option><?php render_grading_category_options($book, is_string($_GET['category_id'] ?? null) ? $_GET['category_id'] : ''); ?></select></label><label><span>Activity</span><select name="activity"><option value="">All activities</option><?php foreach ($book['items'] as $id => $entry): if (!empty($entry['archived'])) continue; ?><option value="<?php echo esc($id); ?>" <?php echo ($_GET['activity'] ?? '') === $id ? 'selected' : ''; ?>><?php echo esc($entry['name']); ?></option><?php endforeach; ?></select></label><label><span>Grading status</span><select name="status"><option value="">All statuses</option><?php foreach (['Not Graded', 'Missing', 'Partial', 'Complete'] as $state): ?><option <?php echo ($_GET['status'] ?? '') === $state ? 'selected' : ''; ?>><?php echo esc($state); ?></option><?php endforeach; ?></select></label><button class="button button-primary">Apply Filters</button></form></details>
    <?php $search = is_string($_GET['q'] ?? null) ? mb_strtolower(trim($_GET['q'])) : ''; $filterItem = is_string($_GET['activity'] ?? null) ? $_GET['activity'] : ''; $filtered = array_values(array_filter($students, function ($student) use ($rows, $search, $filterItem) { $row = $rows[(int) $student['id']]; return ($search === '' || str_contains(mb_strtolower($student['name'] . ' ' . $student['email']), $search)) && (empty($_GET['status']) || $row['status'] === $_GET['status']) && ($filterItem === '' || isset($row['items'][$filterItem])); })); $studentPage = page_records($filtered, 'page', 15); $visibleCategories = array_values(array_filter($book['config']['categories'], fn($category) => empty($_GET['category_id']) || $category['id'] === $_GET['category_id'])); $visibleCategories = array_slice($visibleCategories, 0, 3); ?>
    <table class="grade-table"><caption>Draft gradebook · <?php echo count($filtered); ?> students<?php echo count($book['config']['categories']) > 3 ? ' · Open a student for all categories.' : ''; ?></caption><thead><tr><th scope="col">Student</th><?php foreach ($visibleCategories as $category): ?><th scope="col"><?php echo esc($category['name']); ?></th><?php endforeach; ?><?php if ($filterItem && isset($book['items'][$filterItem])): ?><th scope="col">Activity score</th><?php endif; ?><th scope="col">Overall</th><th scope="col">Status</th></tr></thead><tbody>
    <?php foreach ($studentPage['items'] as $student): $row = $rows[(int) $student['id']]; $byCategory = array_column($row['categories'], null, 'id'); ?><tr><th scope="row"><a href="<?php echo esc($url . '&view=student&student_id=' . (int) $student['id']); ?>"><?php echo esc($student['name']); ?></a></th><?php foreach ($visibleCategories as $category): ?><td data-label="<?php echo esc($category['name']); ?>"><?php echo esc(grade_display($byCategory[$category['id']]['percentage'])); ?></td><?php endforeach; ?><?php if ($filterItem && isset($book['items'][$filterItem])): ?><td data-label="Activity score"><?php echo esc(grade_display($row['items'][$filterItem]['score'] ?? null)); ?></td><?php endif; ?><td data-label="Overall"><strong><?php echo esc(grade_display($row['overall'])); ?></strong><?php if ($row['override']): ?><small>Manually adjusted</small><?php endif; ?></td><td data-label="Status"><?php echo esc($row['status']); ?><?php if ($row['passed'] !== null): ?><small><?php echo $row['passed'] ? 'At or above passing' : 'Below passing'; ?></small><?php endif; ?></td></tr><?php endforeach; ?></tbody></table>
    <?php if (!$filtered): ?><p class="empty-state">No matching enrolled students.</p><?php endif; ?><?php render_pagination($studentPage); ?>
    <p><?php echo $book['published'] ? 'Students currently see the release from ' . esc(format_date($book['published']['at'])) . '. New scores and draft changes require a new release.' : 'Grades are draft. Students cannot see them yet.'; ?></p>
    <details><summary>Publish / Hide Grades</summary><form method="post" class="stack-form" data-grade-dirty><?php render_grade_form_fields($book); ?><input type="hidden" name="action" value="publish"><p>Release this calculation for all enrolled students, including any partial grades. This replaces the previous published release.</p><label><input type="checkbox" name="confirm" value="yes" required> Confirm publishing this grade release</label><button class="button button-primary">Publish Grades</button></form><?php if ($book['published']): ?><form method="post" class="stack-form"><?php render_grade_form_fields($book); ?><input type="hidden" name="action" value="unpublish"><label><input type="checkbox" name="confirm" value="yes" required> Confirm hiding published grades</label><button class="button button-secondary">Hide Grades</button></form><?php endif; ?></details>
</section>
<?php elseif ($view === 'items'): $edit = $item && $item['source'] === 'manual' ? $item : []; ?>
<section class="glass panel"><details <?php echo $error || $edit ? 'open' : ''; ?>><summary><?php echo $edit ? 'Edit manual activity' : 'Add Manual Activity'; ?></summary><form method="post" class="stack-form" data-grade-dirty><?php render_grade_form_fields($book); ?><input type="hidden" name="action" value="item"><input type="hidden" name="item_id" value="<?php echo esc($edit['id'] ?? ''); ?>"><div class="split-fields"><label><span>Activity name</span><input name="name" maxlength="120" required value="<?php echo esc(is_string($_POST['name'] ?? null) ? $_POST['name'] : ($edit['name'] ?? '')); ?>"></label><label><span>Category</span><select name="category_id" required><?php render_grading_category_options($book, is_string($_POST['category_id'] ?? null) ? $_POST['category_id'] : ($edit['category_id'] ?? '')); ?></select></label><label><span>Maximum score</span><input name="max_score" type="number" min="0.01" max="100000" step="0.01" required value="<?php echo esc(is_string($_POST['max_score'] ?? null) ? $_POST['max_score'] : (string) ($edit['max_score'] ?? 100)); ?>"></label><label><span>Date</span><input name="date" type="date" required value="<?php echo esc(is_string($_POST['date'] ?? null) ? $_POST['date'] : ($edit['date'] ?? date('Y-m-d'))); ?>"></label></div><button class="button button-primary">Save Activity</button></form></details>
<?php $itemPage = page_records(array_values($book['items']), 'page', 10); foreach ($itemPage['items'] as $entry): ?><article class="recent-item"><div><strong><?php echo esc($entry['name']); ?></strong><small><?php echo esc($entry['source'] . ' · ' . grade_display($entry['max_score']) . ' points' . (!empty($entry['archived']) ? ' · Archived / not graded' : '')); ?></small></div><div class="action-row"><?php if (empty($entry['archived'])): ?><?php if ($entry['source'] === 'manual'): ?><a class="button button-primary" href="<?php echo esc($url . '&view=entry&item_id=' . $entry['id']); ?>">Enter Scores</a><a class="button button-secondary" href="<?php echo esc($url . '&view=items&item_id=' . $entry['id']); ?>">Edit</a><?php else: ?><a class="button button-secondary" href="/QuizWeb/quiz_builder.php?classroom_id=<?php echo $classroomId; ?>&amp;quiz_id=<?php echo (int) $entry['quiz_id']; ?>">Edit Quiz Grading</a><?php endif; ?><details><summary>Archive</summary><form method="post"><?php render_grade_form_fields($book); ?><input type="hidden" name="action" value="archive"><input type="hidden" name="item_id" value="<?php echo esc($entry['id']); ?>"><p>Exclude this activity from draft grades. Saved scores and earlier published grades remain intact.</p><label><input type="checkbox" name="confirm" value="yes" required> Confirm archive</label><button class="button button-secondary">Archive Activity</button></form></details><?php endif; ?></div></article><?php endforeach; if (!$book['items']): ?><p>No grade items yet. Add a manual activity or assign a quiz category in its builder.</p><?php endif; render_pagination($itemPage); ?></section>
<?php elseif ($view === 'entry'): $entryPage = page_records($students, 'page', 20); ?>
<section class="glass panel"><h2><?php echo esc($item['name'] . ' — ' . grade_display($item['max_score']) . ' points'); ?></h2><p>Tab moves between scores. Blank means Not Yet Graded; zero is a recorded score. Save this page before moving to another page.</p><form method="post" class="stack-form" data-grade-dirty><?php render_grade_form_fields($book); ?><input type="hidden" name="action" value="scores"><input type="hidden" name="item_id" value="<?php echo esc($itemId); ?>"><div class="grade-score-list"><?php foreach ($entryPage['items'] as $student): $sid = (int) $student['id']; $savedScore = $book['scores'][$itemId][(string) $sid] ?? null; $posted = $_POST['scores'][$sid] ?? null; ?><label><span><?php echo esc($student['name']); ?></span><input type="number" name="scores[<?php echo $sid; ?>]" min="0" max="<?php echo esc((string) $item['max_score']); ?>" step="0.01" value="<?php echo esc(is_string($posted) ? $posted : ($savedScore === null ? '' : (string) $savedScore)); ?>" placeholder="Not Yet Graded"><small><?php echo isset($book['overrides'][(string) $sid][$itemId]) ? 'Adjustment active; open student to restore it.' : ($savedScore === null ? 'Not Yet Graded' : 'Graded'); ?></small></label><?php endforeach; ?></div><div class="action-row builder-toolbar"><button class="button button-primary">Save Scores</button><a class="button button-secondary" href="<?php echo esc($url . '&view=items'); ?>">Back to Activities</a></div></form><?php render_pagination($entryPage); ?></section>
<?php elseif ($view === 'student'): $selectedStudent = array_values(array_filter($students, fn($student) => (int) $student['id'] === $studentId))[0]; $grade = $rows[$studentId]; ?>
<header class="page-heading"><h2><?php echo esc($selectedStudent['name']); ?></h2><a class="button button-secondary" href="<?php echo esc($url); ?>">Back to Gradebook</a></header>
<?php render_grade_breakdown($grade, $book['config']); ?>
<section class="glass panel"><details <?php echo $error ? 'open' : ''; ?>><summary>Adjust / Restore a Grade</summary><form method="post" class="stack-form" data-grade-dirty><?php render_grade_form_fields($book); ?><input type="hidden" name="student_id" value="<?php echo $studentId; ?>"><label><span>Grade to adjust</span><select name="item_id"><option value="overall">Overall grade (0–100)</option><?php foreach ($grade['items'] as $id => $entry): ?><option value="<?php echo esc($id); ?>" <?php echo ($_POST['item_id'] ?? '') === $id ? 'selected' : ''; ?>><?php echo esc($entry['name'] . ' (0–' . $entry['max_score'] . ')'); ?></option><?php endforeach; ?></select></label><label><span>Adjusted value (leave blank when restoring)</span><input name="value" type="number" min="0" max="100000" step="0.01" value="<?php echo esc(is_string($_POST['value'] ?? null) ? $_POST['value'] : ''); ?>"></label><label><span>Note (shared with student when published, optional)</span><textarea name="reason" maxlength="500" rows="2"><?php echo esc(is_string($_POST['reason'] ?? null) ? $_POST['reason'] : ''); ?></textarea></label><div class="action-row"><button class="button button-primary" name="action" value="override">Save Adjustment</button><button class="button button-secondary" name="action" value="restore">Restore Automatic Grade</button></div></form><p>Item adjustments use score units; the overall adjustment uses percentage. The original calculation and change history are preserved.</p></details></section>
<section class="glass panel"><details><summary>Quiz Attempt History</summary><?php $history = array_values(array_filter($attempts, fn($attempt) => (int) $attempt['student_id'] === $studentId)); $historyPage = page_records($history, 'attempt_page', 10); foreach ($historyPage['items'] as $attempt): ?><div class="recent-item"><strong><?php echo esc($attempt['quiz_title']); ?></strong><span><?php echo esc($attempt['score'] . '/' . $attempt['max_score'] . ' · ' . format_date($attempt['played_at'])); ?></span><a class="button button-secondary" href="/QuizWeb/results.php?id=<?php echo (int) $attempt['id']; ?>">View Attempt</a></div><?php endforeach; if (!$history): ?><p>No attempts yet.</p><?php endif; render_pagination($historyPage); ?></details></section>
<?php elseif ($view === 'analytics'): $numeric = array_values(array_filter(array_column($rows, 'overall'), fn($value) => $value !== null)); ?>
<section class="glass panel"><h2>Draft grade analysis</h2><div class="learning-summary-grid"><article class="stat-card"><strong><?php echo $numeric ? esc(grade_display(array_sum($numeric) / count($numeric))) : '—'; ?></strong><span>Class average (<?php echo count($numeric); ?> graded students)</span></article><article class="stat-card"><strong><?php echo count(array_filter($rows, fn($row) => $row['status'] === 'Complete')); ?>/<?php echo count($students); ?></strong><span>Complete gradebooks</span></article></div>
<h3>Grade distribution</h3><?php foreach ($book['config']['scale'] as $band): ?><p><?php echo esc($band['label']); ?>: <?php echo count(array_filter($rows, fn($row) => $row['scale_label'] === $band['label'])); ?> students</p><?php endforeach; ?>
<h3>Category averages</h3><?php foreach ($book['config']['categories'] as $category): $values = []; foreach ($rows as $row) foreach ($row['categories'] as $calculatedCategory) if ($calculatedCategory['id'] === $category['id'] && $calculatedCategory['percentage'] !== null) $values[] = $calculatedCategory['percentage']; ?><p><?php echo esc($category['name']); ?>: <?php echo $values ? esc(grade_display(array_sum($values) / count($values))) . '%' : 'Not Graded'; ?></p><?php endforeach; ?>
<h3>Activity performance</h3><?php $performance = []; foreach ($book['items'] as $id => $entry) { if (!empty($entry['archived'])) continue; $values = []; foreach ($rows as $row) if (isset($row['items'][$id]) && $row['items'][$id]['percentage'] !== null) $values[] = $row['items'][$id]['percentage']; $performance[] = ['name' => $entry['name'], 'average' => $values ? array_sum($values) / count($values) : null, 'count' => count($values)]; } usort($performance, fn($a, $b) => ($a['average'] ?? INF) <=> ($b['average'] ?? INF)); $performancePage = page_records($performance); foreach ($performancePage['items'] as $entry): ?><p><?php echo esc($entry['name']); ?> · <?php echo esc(grade_display($entry['average'])); ?>% · <?php echo $entry['count']; ?>/<?php echo count($students); ?> graded</p><?php endforeach; render_pagination($performancePage); ?></section>
<?php elseif ($view === 'audit'): $auditPage = max(1, (int) ($_GET['page'] ?? 1)); $query = db()->prepare('SELECT COUNT(*) FROM grade_changes WHERE classroom_id = ?'); $query->execute([$classroomId]); $total = (int) $query->fetchColumn(); $auditPage = min($auditPage, max(1, (int) ceil($total / 15))); $query = db()->prepare('SELECT * FROM grade_changes WHERE classroom_id = ? ORDER BY id DESC LIMIT 15 OFFSET ' . (($auditPage - 1) * 15)); $query->execute([$classroomId]); ?>
<section class="glass panel"><p>Changes record the actor, student, activity, previous/new value, and timestamp.</p><?php foreach ($query->fetchAll() as $change): ?><details class="grade-audit-row"><summary><?php echo esc(ucfirst($change['action']) . ' · ' . format_date($change['created_at'])); ?></summary><p>Teacher #<?php echo (int) $change['actor_id']; ?> · Student <?php echo $change['student_id'] === null ? '—' : '#' . (int) $change['student_id']; ?> · Activity <?php echo esc($change['item_id'] ?? 'Class grading'); ?></p><pre><?php echo esc('Previous: ' . $change['previous_value'] . "\nNew: " . $change['new_value']); ?></pre></details><?php endforeach; if (!$total): ?><p>No grading changes yet.</p><?php endif; render_pagination(['page' => $auditPage, 'pages' => max(1, (int) ceil($total / 15)), 'key' => 'page']); ?></section>
<?php endif; ?>
<script>window.gradingPostedDraft = <?php echo $error ? 'true' : 'false'; ?>;</script>
<?php render_footer(['/QuizWeb/assets/js/grading.js']); ?>
