<?php
$meta = academic_meta($classroom);
$displayPeriods = $book['config']['periods'] ?? academic_periods();
$complete = count(array_filter($rows, fn($row) => $row['status'] === 'Complete'));
$notStarted = count(array_filter($rows, fn($row) => in_array($row['status'], ['Not Started', 'Not Graded', 'Missing'], true)));
$query = is_string($_GET['q'] ?? null) ? mb_strtolower(trim($_GET['q'])) : '';
$statusFilter = is_string($_GET['status'] ?? null) ? $_GET['status'] : '';
$periodFilter = is_string($_GET['period'] ?? null) && in_array($_GET['period'], ['prelim', 'midterm', 'finals'], true) ? $_GET['period'] : '';
$sort = is_string($_GET['sort'] ?? null) && in_array($_GET['sort'], ['name', 'highest', 'lowest'], true) ? $_GET['sort'] : 'name';
$filtered = array_values(array_filter($students, function ($student) use ($query, $statusFilter, $periodFilter, $rows) {
    $row = $rows[(int) $student['id']];
    $state = $periodFilter ? ($row['periods'][$periodFilter]['status'] ?? 'Not Graded') : $row['status'];
    return ($query === '' || str_contains(mb_strtolower($student['name']), $query)) && ($statusFilter === '' || $statusFilter === $state);
}));
usort($filtered, function ($a, $b) use ($rows, $sort, $periodFilter) {
    if ($sort === 'name') return [$a['name'], $a['id']] <=> [$b['name'], $b['id']];
    $value = fn($student) => $periodFilter ? ($rows[$student['id']]['periods'][$periodFilter]['overall'] ?? null) : $rows[$student['id']]['overall'];
    $av = $value($a); $bv = $value($b);
    if ($av === null || $bv === null) return ($av === null ? 1 : 0) <=> ($bv === null ? 1 : 0);
    return ($sort === 'highest' ? $bv <=> $av : $av <=> $bv) ?: ($a['id'] <=> $b['id']);
});
$size = in_array((int) ($_GET['per_page'] ?? 8), [8, 15, 30], true) ? (int) ($_GET['per_page'] ?? 8) : 8;
$studentPage = page_records($filtered, 'page', $size);
?>
<div class="academic-context"><span><?php echo esc(($meta['subject_code'] ?: $classroom['subject']) . ' · ' . $meta['academic_year'] . ' · ' . $meta['semester']); ?></span><a href="/QuizWeb/classroom_settings.php?classroom_id=<?php echo $classroomId; ?>">Class settings</a></div>
<?php if ($meta['academic_year'] === 'Unassigned'): ?><p class="academic-notice">Set this classroom’s academic year and semester in Class settings to include it in a semester result.</p><?php endif; ?>
<div class="academic-top-grid">
    <section class="glass panel academic-config"><div class="academic-panel-heading"><h2>Class grading configuration</h2><a class="button button-secondary" href="<?php echo esc($url . '&view=setup'); ?>">Edit Weights</a></div><?php if (empty($book['config']['periods'])): ?><p class="academic-notice">Existing category-based grades are preserved. Enable grading periods and assign older activities in Edit Weights to calculate Prelim, Midterm, and Finals.</p><?php else: ?><div class="academic-period-cards"><?php foreach ($displayPeriods as $period): ?><article><span class="academic-period-dot" data-period="<?php echo esc($period['id']); ?>"></span><strong><?php echo esc($period['name']); ?> (<?php echo esc(grade_display($period['weight'])); ?>%)</strong><progress max="100" value="<?php echo esc((string) $period['weight']); ?>" aria-label="<?php echo esc($period['name']); ?> weight"></progress><small><?php echo esc(implode(', ', array_column($book['config']['categories'], 'name'))); ?></small></article><?php endforeach; ?></div><?php endif; ?></section>
    <section class="glass panel academic-stats"><h2>Class statistics</h2><div class="academic-stat-grid"><?php foreach (['Total students' => count($students), 'Complete' => $complete, 'Partial / incomplete' => count($students) - $complete - $notStarted, 'Not started' => $notStarted] as $label => $value): ?><article><strong><?php echo $value; ?></strong><span><?php echo esc($label); ?></span></article><?php endforeach; ?></div></section>
</div>
<section class="glass panel academic-gradebook">
<div class="academic-panel-heading"><h2>Student gradebook</h2><span class="academic-status"><?php echo !empty($book['locked']) ? 'Finalized · locked' : (!empty($book['reviewed']) && hash_equals((string) $book['reviewed']['hash'], academic_review_hash($book, $classroom, $attempts)) ? 'Reviewed draft' : 'Calculated draft'); ?></span></div>
<form method="get" class="academic-filter-bar"><input type="hidden" name="classroom_id" value="<?php echo $classroomId; ?>"><input type="hidden" name="view" value="overview"><label><span>Search student</span><input type="search" name="q" value="<?php echo esc($query); ?>" placeholder="Search student…"></label><label><span>Period</span><select name="period"><option value="">All periods</option><?php foreach (academic_periods() as $period): ?><option value="<?php echo esc($period['id']); ?>" <?php echo $periodFilter === $period['id'] ? 'selected' : ''; ?>><?php echo esc($period['name']); ?></option><?php endforeach; ?></select></label><label><span>Status</span><select name="status"><option value="">All statuses</option><?php foreach (['Complete', 'Partial', 'Not Started', 'Not Graded', 'Missing', 'Incomplete', 'Withdrawn'] as $state): ?><option <?php echo $statusFilter === $state ? 'selected' : ''; ?>><?php echo esc($state); ?></option><?php endforeach; ?></select></label><label><span>Sort</span><select name="sort"><?php foreach (['name' => 'Student name', 'highest' => 'Highest grade', 'lowest' => 'Lowest grade'] as $value => $label): ?><option value="<?php echo esc($value); ?>" <?php echo $sort === $value ? 'selected' : ''; ?>><?php echo esc($label); ?></option><?php endforeach; ?></select></label><label><span>Per page</span><select name="per_page"><?php foreach ([8,15,30] as $limit): ?><option <?php echo $size === $limit ? 'selected' : ''; ?>><?php echo $limit; ?></option><?php endforeach; ?></select></label><button class="button button-secondary">Apply</button><a class="button button-secondary" href="<?php echo esc($url . '&export=csv'); ?>">Export CSV</a></form>
<div class="academic-table-scroll"><table class="academic-table"><caption><?php echo count($filtered); ?> students · Draft grades</caption><thead><tr><th>#</th><th>Student name</th><?php foreach ($displayPeriods as $period): ?><th class="<?php echo $periodFilter === $period['id'] ? 'is-selected-period' : ''; ?>"><?php echo esc($period['name']); ?><small><?php echo !empty($book['config']['periods']) ? esc(grade_display($period['weight'])) . '%' : 'Not configured'; ?></small></th><?php endforeach; ?><th>Final grade</th><th>Status</th><th>Action</th></tr></thead><tbody>
<?php foreach ($studentPage['items'] as $index => $student): $row = $rows[(int) $student['id']]; ?><tr><td><?php echo ($studentPage['page'] - 1) * $size + $index + 1; ?></td><th><span class="academic-avatar"><?php echo esc(mb_substr($student['name'], 0, 1)); ?></span><?php echo esc($student['name']); ?></th><?php foreach ($displayPeriods as $period): ?><td class="<?php echo $periodFilter === $period['id'] ? 'is-selected-period' : ''; ?>"><?php echo esc(grade_display($row['periods'][$period['id']]['overall'] ?? null)); ?></td><?php endforeach; ?><td><strong class="academic-grade-value"><?php echo esc(grade_display($row['overall'])); ?></strong></td><td><span class="academic-status <?php echo $row['status'] === 'Complete' ? 'is-complete' : 'is-pending'; ?>"><?php echo esc($row['status']); ?></span></td><td><button type="button" class="button button-secondary" data-open-grade="student-<?php echo (int) $student['id']; ?>">View Details</button></td></tr><?php endforeach; ?>
<?php if (!$filtered): ?><tr><td colspan="8" class="academic-empty">No students match your filters.</td></tr><?php endif; ?></tbody></table></div><?php render_pagination($studentPage); ?>
</section>
<?php foreach ($studentPage['items'] as $student): $row = $rows[(int) $student['id']]; ?>
<dialog class="academic-drawer" id="student-<?php echo (int) $student['id']; ?>" aria-labelledby="student-title-<?php echo (int) $student['id']; ?>"><header><h2 id="student-title-<?php echo (int) $student['id']; ?>"><?php echo esc($student['name']); ?></h2><button type="button" class="academic-close" data-close-grade aria-label="Close grade breakdown">×</button></header><div class="academic-drawer-body"><?php render_grade_breakdown($row, $book['config']); ?><a class="button button-secondary" href="<?php echo esc($url . '&view=student&student_id=' . $student['id']); ?>">Assessment Corrections &amp; History</a></div></dialog>
<?php endforeach; ?>
<?php require __DIR__ . '/academic_release_view.php'; ?>
