<section class="glass panel academic-release"><div class="academic-panel-heading"><h2>Grade release</h2><span class="academic-status"><?php echo !empty($book['locked']) ? 'Finalized · locked' : ($book['published'] ? 'Published' : 'Draft'); ?></span></div>
<p class="muted">Review the calculated grades, publish a student release, then finalize when every period is complete.</p>
<?php if (!empty($book['locked'])): ?>
<form method="post" class="academic-inline-form"><?php render_grade_form_fields($book); ?><input type="hidden" name="action" value="unlock"><label><span>Reason for reopening grades</span><input name="reason" maxlength="500" required></label><button class="button button-secondary">Unlock for Correction</button></form>
<?php else: ?>
<div class="academic-release-grid"><form method="post" class="stack-form"><?php render_grade_form_fields($book); ?><input type="hidden" name="action" value="review"><h3>1. Review</h3><p>Confirm you have checked the calculated grades and assessments.</p><button class="button button-secondary">Mark Grades Reviewed</button></form>
<form method="post" class="stack-form"><?php render_grade_form_fields($book); ?><input type="hidden" name="action" value="publish"><h3>2. Publish</h3><label class="grade-confirm"><input type="checkbox" name="confirm" value="yes" required><span>Release the reviewed grades to students</span></label><button class="button button-primary">Release Grades</button></form>
<form method="post" class="stack-form"><?php render_grade_form_fields($book); ?><input type="hidden" name="action" value="lock"><h3>3. Finalize</h3><label class="grade-confirm"><input type="checkbox" name="confirm" value="yes" required><span>Finalize this release and lock grade editing</span></label><button class="button button-secondary">Finalize &amp; Lock</button></form></div>
<?php if ($book['published']): ?><details><summary>Hide published release</summary><form method="post" class="academic-inline-form"><?php render_grade_form_fields($book); ?><input type="hidden" name="action" value="unpublish"><label class="grade-confirm"><input type="checkbox" name="confirm" value="yes" required><span>Confirm hiding published grades</span></label><button class="button button-secondary">Hide Grades</button></form></details><?php endif; ?>
<?php endif; ?></section>
