<?php

// Administrative records contain no credentials or session identifiers.
function ensure_admin_schema(PDO $pdo): void
{
    $pdo->exec("ALTER TABLE users ADD COLUMN IF NOT EXISTS account_status VARCHAR(20) NOT NULL DEFAULT 'active'");
    $pdo->exec("CREATE TABLE IF NOT EXISTS audit_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        actor_id BIGINT, target_id BIGINT, action VARCHAR(80) NOT NULL,
        occurred_at VARCHAR(40) NOT NULL
    )");
    $pdo->exec('CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action, id)');
}

function record_audit(string $action, ?int $actorId = null, ?int $targetId = null): void
{
    $statement = db()->prepare('INSERT INTO audit_logs (actor_id, target_id, action, occurred_at) VALUES (?, ?, ?, ?)');
    $statement->execute([$actorId, $targetId, $action, now_iso()]);
}

function admin_set_account_status(PDO $pdo, int $actorId, int $targetId, string $status): void
{
    if (!in_array($status, ['active', 'suspended'], true) || $actorId === $targetId) {
        throw new InvalidArgumentException('Choose another account and a valid status.');
    }
    $pdo->beginTransaction();
    try {
        $actorQuery = $pdo->prepare('SELECT role, account_status FROM users WHERE id = ? FOR UPDATE');
        $actorQuery->execute([$actorId]);
        $actor = $actorQuery->fetch();
        if (!$actor || $actor['role'] !== 'admin' || $actor['account_status'] !== 'active') {
            throw new InvalidArgumentException('Administrator access is required.');
        }
        $query = $pdo->prepare('SELECT role FROM users WHERE id = ? FOR UPDATE');
        $query->execute([$targetId]);
        $target = $query->fetch();
        if (!$target || $target['role'] === 'admin') {
            throw new InvalidArgumentException('Administrator accounts cannot be changed here.');
        }
        $update = $pdo->prepare('UPDATE users SET account_status = ? WHERE id = ?');
        $update->execute([$status, $targetId]);
        $audit = $pdo->prepare('INSERT INTO audit_logs (actor_id, target_id, action, occurred_at) VALUES (?, ?, ?, ?)');
        $audit->execute([$actorId, $targetId, 'account_' . $status, now_iso()]);
        $pdo->commit();
    } catch (Throwable $error) {
        $pdo->rollBack();
        throw $error;
    }
}
